server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://192.168.254.31:3306/OTO3?useUnicode=true&characterEncoding=utf-8
    username: devuser
    password: Userd@v2018
    driverClassName: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.example.demo.**.dao
  mapper-locations: classpath:**/*.xml